
// user action types
export const SET_USER = 'SET_USER'
export const CLEAR_USER = 'CLEAR_USER'

// request action types
export const REQUESTS_LIST_LOADING     = 'REQUESTS_LIST_LOADING'
export const REQUESTS_LIST_LOADED      = 'REQUESTS_LIST_LOADED'
export const REQUESTS_LIST_LOAD_FAILED = 'REQUESTS_LIST_LOAD_FAILED'

// historyRequests action types
export const HISTORY_REQUESTS_LIST_LOADING     = 'HISTORY_REQUESTS_LIST_LOADING'
export const HISTORY_REQUESTS_LIST_LOADED      = 'HISTORY_REQUESTS_LIST_LOADED'
export const HISTORY_REQUESTS_LIST_LOAD_FAILED = 'HISTORY_REQUESTS_LIST_LOAD_FAILED'

//claim action type
export const CLAIMING_LIST_LOADING     = 'CLAIMING_LIST_LOADING'
export const CLAIMING_LIST_LOADED      = 'CLAIMING_LIST_LOADED'
export const CLAIMING_LIST_LOAD_FAILED = 'CLAIMING_LIST_LOAD_FAILED'

// export const CHANGE_PAGE_OF_REQUESTS   = 'CHANGE_PAGE_OF_REQUESTS'
